doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '14'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            # App:
            #     is_bundle: false
            #     dir: '%kernel.project_dir%/src/Entity'
            #     prefix: 'App\Entity'
            #     alias: App
            App\Domain:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain'
                prefix: 'App\Domain'
                alias: Domain


            # gedmo_translatable:
            #     type: annotation
            #     prefix: Gedmo\Translatable\Entity
            #     dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translatable/Entity"
            #     alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
            #     is_bundle: false
            # gedmo_translator:
            #     type: annotation
            #     prefix: Gedmo\Translator\Entity
            #     dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translator/Entity"
            #     alias: GedmoTranslator # (optional) it will default to the name set for the mapping
            #     is_bundle: false
           # gedmo_loggable:
           #     type: annotation
           #     prefix: Gedmo\Loggable\Entity
           #     dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
           #     alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
           #     is_bundle: false
           #  gedmo_tree:
           #      type: annotation
           #      prefix: Gedmo\Tree\Entity
           #      dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
           #      alias: GedmoTree # (optional) it will default to the name set for the mapping
           #      is_bundle: false


        dql:
            datetime_functions:
                NOW: DoctrineExtensions\Query\Mysql\Now
                EXTRACT: DoctrineExtensions\Query\Postgresql\ExtractFunction
                TO_CHAR: DoctrineExtensions\Query\Postgresql\DateFormat
            string_functions:
                LPAD: DoctrineExtensions\Query\Mysql\Lpad
                CAST: DoctrineExtensions\Query\Mysql\Cast
            numeric_functions:
                RANDOM: DoctrineExtensions\Query\Sqlite\Random
                ROUND: DoctrineExtensions\Query\Mysql\Round

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
