framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            # async_priority_high:
            #     dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            #     retry_strategy:
            #         max_retries: 3
            #         multiplier: 2
            #     options:
            #         exchange:
            #             name: high

            # async:
            #     dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            #     retry_strategy:
            #         max_retries: 3
            #         multiplier: 2

            # async_priority_low:
            #     dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            #     retry_strategy:
            #         max_retries: 3
            #         multiplier: 2
            #     options:
            #         exchange:
            #             name: low

            # liip_imagine:
            #     dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            #     retry_strategy:
            #         max_retries: 3
            #         multiplier: 2

            # failed: 'doctrine://default?queue_name=failed'

        routing:
            # Symfony\Component\Mailer\Messenger\SendEmailMessage: async_priority_high
            # Symfony\Component\Notifier\Message\ChatMessage: async_priority_high
            # Symfony\Component\Notifier\Message\SmsMessage: async_priority_low
            # Liip\ImagineBundle\Message\WarmupCache: liip_imagine
            # Route your messages to the transports
            # 'App\Message\YourMessage': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
