twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        enabled_locales: '%kernel.enabled_locales%'
        page: '@App\Http\Twig\PageVariable'

    form_themes: ['bootstrap_5_layout.html.twig']

    paths:
        '%kernel.project_dir%/src/Infrastructure/Maker/templates': maker

when@test:
    twig:
        strict_variables: true
