controllers:
  resource: ../src/Http/Controller/
  type: attribute
  prefix: /{_locale}
  # name_prefix: app_
admin_controllers:
  name_prefix: admin_
  prefix: '%admin_prefix%'
  resource: ../src/Http/Admin/Controller/
  type: attribute
api_controllers:
  name_prefix: api_
  prefix: /api
  resource: ../src/Http/Api/Controller/
  type: attribute
