# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    container.dumper.inline_factories: true
    app.locale: 'fr'
    locale: 'fr'
    app.allowed_locales: ['fr', 'en']
    app.locales: fr|en
    admin_prefix: '%env(resolve:ADMIN_PREFIX)%'
    image_resize_key: '%env(resolve:IMAGE_RESIZE_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $projectDir: '%kernel.project_dir%'
            string $adminPrefix: '%admin_prefix%'


    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Infrastructure/Migrations'

    App\Http\Controller\:
        resource: '../src/Http/Controller'
        tags: ['controller.service_arguments']

    App\Http\Admin\Controller\:
        resource: '../src/Http/Admin/Controller'
        tags: ['controller.service_arguments']

    App\Http\Api\Controller\:
        resource: '../src/Http/Api/Controller'
        tags: ['controller.service_arguments']

    App\Http\Api\Processor\CommentProcessor:
        bind:
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'
            $removeProcessor: '@api_platform.doctrine.orm.state.remove_processor'

    # app_page_variable:
    #     class: Twig\Environment
    #     calls:
    #         - addGlobal: ['page', '@App\Http\Twig\PageVariable']

    App\Helper\Paginator\PaginatorInterface:
        class: App\Helper\Paginator\KnpPaginator

    Knp\Bundle\PaginatorBundle\Helper\Processor: ~

    App\Http\Grid\Blog\PostGrid:
        tags: ['prezent_grid.grid']

    App\Infrastructure\Image\ImageResizer:
        arguments: ['%image_resize_key%']






